### ISSUE TITLE
Footnotes inside tables stops document from compiling

### ISSUE THREAD

**Issue by meikal** [langsci/langscibook#121]
Hi,

i'm using the [CTAN version of langscibook](https://www.ctan.org/pkg/langsci) for a large book project. I generate most LateX code automatically using [MultiMarkdown](https://fletcherpenney.net/multimarkdown/). I noticed that the `langscibook`-class seems to have issues with the table structures generated by MultiMarkdown, which creates nested enviroments of a`tabulary`inside a `minpage`inside a `table`-environment:

```
test

\begin{table}[htbp]
\begin{minipage}{\linewidth}
\setlength{\tymax}{0.5\linewidth}
\centering
\small
\caption{test}
\label{test}
\begin{tabulary}{\textwidth}{@{}lll@{}} \toprule
 test\footnote{test} & test\footnote{test} & test\footnote{test} \\
\midrule

 test\footnote{test} & test\footnote{test} & test\footnote{test} \\
 test\footnote{test} & test\footnote{test} & test\footnote{test} \\
 test\footnote{test} & test\footnote{test} & test\footnote{test} \\
 test\footnote{test} & test\footnote{test} & test \\
 test                & test                & test \\
 test                & test                & test \\
 
\bottomrule

\end{tabulary}
\end{minipage}
\end{table}

test
```

If I put this inside e.g. inside a `\documentclass{article}` it compiles just fine, but if I put it inside the [template on Overleaf](https://www.overleaf.com/latex/templates/langsci-template-for-monographs-2020-slash-05/jjyhwqfcmbgx) the compile never finishes. The same happens on a local machine which makes me think there is some kind of infinite loop.

If I remove just *one* of the footnotes it compiles again (it also compiles if I remove the surrounding `table` and `minipage`-enviroments), which makes me think that this error relates to footnotes running out of the float.

Thanks for the support.

**Comment by Glottotopia** [comment]
if you replace `tabulary` with `tabularx`, the problem seems to disappear. 

In general, we advise against footnotes in tables. 

This problem only seems to occur when a package which we officially do not support (`tabulary`) is combined with a practice we advise against (footnotes in tables).

**Comment by kopeckyf** [comment]
The issue is unrelated to `langscibook`, and I don't think there is anything we can do about it. A variant of this issue [was discussed here](https://tex.stackexchange.com/questions/186991/duplicate-footnotes-when-tabulary-is-inside-minipage). To quickly summarise:  `tabulary` passes its table one time before outputting it to the page. In this first pass, it raises the `footnote` counter. 

There are 14 footnotes in your table, so when the typesetting begins, the `footnote` counter of the first footnote is 15, output by `\alph` as _o_. The counter is then raised until it reaches 26, which is the maximum state that `\alph`, responsible to the conversion of counters to letters (alphabetic counting), can handle. As soon as any counter hits 27 or more, `\alph` does not know what to do about it and raises an error.  

If you copy your table to a minimal document, you'll see the error appearing, though with a more verbose message than in `langscibook`:

```
\documentclass{article}
\usepackage{booktabs,tabulary}
\begin{document}
  \begin{table}
  ...
  \end{table}
\end{document}
```

**Comment by kopeckyf** [comment]
On a different note, there seem to be many problems with the conversion result from your Markdown converter. Of course we know from first-hand experience that converting documents is no trivial business, which is why we routinely apply post-processing to many elements after conversion, including tables. 

Let me go through the header of the output table. If you have any control over the table header template of your converter, it would probably be worthwhile to improve that template:

- `\begin{table}[htbp]`
Specifying `htbp` here is equivalent to giving no optional argument to table. 

`- \begin{minipage}{\linewidth}`
Nesting the table inside a `minipage` is unnecessary in any `langscibook` document.

- `\setlength{\tymax}{0.5\linewidth}`
This setting only applies to the `tabulary` columns, which are L, C, R and J. None of these were given in the following table layout.

- `\centering`
If the `minipage` is deleted, this can be deleted as well. Btw, tables are automatically centred in `langscibook`.

- `\small`
Should not be the default output of the converter, but only manually applied to tables that really need this. Cell contents should not be in smaller font by default.


- `\caption{test}  \label{test}`

It is usually a  good idea to place `\label` inside `\caption`. This improves the behaviour of hyperlinks.

- `\begin{tabulary}{\textwidth}{@{}lll@{}} \toprule`
Please don't use `@{}` before the first and after the last column. The separator of table columns is defined in `langscibook` and part of the lay out. 

It is pointless to use the `tabulary` environment without specifying any `tabulary` columns, that is the upper case variants L, C, R or J. There won't be any of the automatic adjustments taking place if none of these is present in your table definition. 

So you could come to the same output by just using `\begin{tabular}{lll}`,

**Comment by meikal** [comment]
Dear Felix,

thank you for your very helpful replies. It took me some time to digest them, but eventually they allowed me to understand the cause of these issues.

It is a fact though, that these issues occur when compiling using the langscibook-class, but I understand that it may be out of scope of your work.

In regard to the problematic conversion results - I agree with you, but it is the standard Multi-Markdown compiler, which is the only compiler available in Scrivener able to produce LaTeX, which is the software I use for writing. 

I was planing on cleaning up the code semi-automatically using some text editor and regular expressions before submission, but I don’t have any tools at hand to influence the code automatically at the the time of compilation or just after. Do you have any suggestions on how to do that?

**Comment by kopeckyf** [comment]
Hey there,

if you wanted some optimisation you could definitely replace the `tabulary` environments with `tabularx`. If there is any `Y` column in the tables, you can safely replace them with `Q`. You could then disable loading of `\usepackage{tabulary}`.

We'll be very happy to look at your submission and see if there are more ways to optimise the manuscript. But that is hard to judge without a proper look at it. It's important to stress that optimisation is not necessary before submitting your manuscript. It would be best if you could submit your TeX-converted manuscript as soon as you are satisfied with the version you see in Scrivener, and we'll happily take it from there. (If you hand in the converted manuscript, it would be ideal if you could accompany it with an "authoritative" PDF export from Scrivener and/or the original `.md` file)
