### ISSUE TITLE
Unify the input and appearance of footnotes in tables

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#126]
Footnotes in tabularx environment are not printed out. The footnote in tabularx increments the counter, but is not printed out. The result is that the footnote in tabular gets the wrong counter, and the footnotes skip one number afterwards. 

expected behavior: All footnote texts should be printed out, and the counters should increment regularly

```
  Footnote not in a tabular\footnote{I am not in a tabular}

  \begin{tabular}{|l|}
  \hline
    Footnote  in a tabular\footnote{I am in a tabular}\\
  \hline
  \end{tabular}

  \begin{tabularx}{\textwidth}{|l|}
  \hline
    Footnote  in a tabularx\footnote{I am in a tabular}\\
  \hline
  \end{tabularx}

  Footnote at the very end\footnote{I am the last one!}
```

Output: 

![Screenshot_2020-09-18_09-46-47](https://user-images.githubusercontent.com/1553576/93570837-e5416b80-f993-11ea-87b2-865cc48ac606.png)

**Comment by Glottotopia** [comment]
In former versions of langscibook.cls, the behavior was as intended

**Comment by Glottotopia** [comment]
has been confirmed in another book

**Comment by kopeckyf** [comment]
Looking at the output you posted, it seems that it is the `\footnote` in the `\begin{tabular}`, not the one in the `\begin{tabularx}` that is not printed. 

This can be traced back to a rather minimal document:

```latex
\documentclass{article}
\usepackage{tabularx}

\begin{document}
  \begin{tabular}{ll}
    Hello & World\footnote{I am in a tabular}\\
  \end{tabular}

  \begin{tabularx}{\textwidth}{lX}
    Hello & World\footnote{I am in a tabularx}\\
  \end{tabularx}
\end{document}
```

The output of the above shows one footnote - the one from the `tabularx`.

A well known circumvention of this issue is to use `\footnotemark` and `\footnotetext`. This solution is handy if there are only a few footnotes in a table. It can get rather messy when there are more than a few.

**Comment by kopeckyf** [comment]
In `langscibook`, the behaviour is improved somewhat but not much. The current behaviour of our class depends on whether a `\begin{table}` environment is provided or not:

## Case 1: tabular without table => Bad
A numeric footnote marker is placed, but no footnote is shown.

## Case 2: tabular within table => Good
When nested in a `\begin{table} \begin{tabular}`, footnotes produce alphabetic indicators and the footnote is printed.

## Case 3: tabularx without a table env  => OK
A numeric footnote marked is placed and the footnote is shown at the bottom of the page. Not ideal, but OK.

## Case 4: tabularx within a table env => Bad
An alphabetic indicator is printed, but the footnote is omitted 

## Solutions for Cases 1 & 4
Using `\footnotemark` and placing `\footnotetext` **after** `\end{table}` will produce a footnote at the end of the page. This is not ideal, because there are cases in which this can lead to the table being printed on a different page than the footnote => Very bad.

I think this summarises the problem quite well. There's certainly work ahead on this one.

**Comment by Glottotopia** [comment]
The issue is related to the load order of `hyperref` and `tabularx`. `tabularx` must be loaded AFTER `hyperref`. Then, the footnotes work in floats for `tabularx` environments. 

The footnotes continue to be broken for `tabularx` outside of floats, but this is a very uncommon use case.

**Comment by kopeckyf** [comment]
Interesting - the `hyperref` documentation has a few lines on this, stating it was incompatible with footnotes in `tabularx`. The `tabularx` documentation is silent on all of this, but the load order fix suggests that they might have some sort of fix in `tabularx`.

For sake of completeness: The solution that the `hyperref` documentation proposes is to disable references to footnotes completely with:

```latex
\usepackage[hyperfootnotes=false, ...]{hyperref}
```
Given that references from footnote indicators to footnote bodies on the same page, this probably would not have too much influence on usability.
