### ISSUE TITLE
langsci-gb4e resets footnotes

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#135]
`\emph{Blabla\footnote{Footnote.} bla.}` comes out as italics, even if no `exe`, `\ea`, `\gll` or similar is involved. 

Expected result: Footnotes should not be affected by the formatting of the character after which they are called. 

Possible solution: 
comment out 
```
 \@ifundefined{new@fontshape}{\def\reset@font{}\let\mathrm\rm\let\mathit\mit}{}
``` 
in line 82 of  `langsci-gb4e.sty`

**Comment by Glottotopia** [comment]
this behaviour does not occur with `\documentclass{langscibook}` but it does occur with `\documentclass{article}`, and presumable all other cls.

**Comment by kopeckyf** [comment]
Some background: `\new@fontshape` is related to the New Font Selection Scheme (NFSS) that was introduced in LaTeX 2e (a long time ago). The NFSS provides commands such as `\textit`, `\itshape` instead of `\it`, etc. 

Testing for the presence of `\new@fontshape` effectively tests whether the NFSS is present. The only case I can imagine when this is not the case is when a TeX version prior to 2e is used. So if someone goes trough their attic and finds a Macintosh II or a similar system, that would be relevant.

Simply commenting this out seems a little dirty. I'd rather revamp `gb4e` to be up to date with current (as in "younger than 20 years") TeX distributions or switch to an example pkg that is build for these systems.

**Comment by kopeckyf** [comment]
One more thought. I think the culprit here is `\def\reset@font{}`, i.e. moving `\reset@font` to mean nothing. `\reset@font` is the internal LaTeX name for `\normalfont`. 

Reconfiguring such commands is extremely bad design. It should never have been pushed into `gb4e`.

**Comment by Glottotopia** [comment]
I think it is admissible to break backward compatibility to the mentioned Macintosh II machines and remove the NFSS check altogether. This will solve a problem that real people are having (outside of our class).

**Comment by kopeckyf** [comment]
There's also nothing in the vicinity of Line 82. No comments, no doc, no context. Very strange. I think you can nuke it.

**Comment by kopeckyf** [comment]
Closed by @Glottotopia in https://github.com/langsci/langscibook/commit/c55abeb2cbe8f29b18271d8262e2d6d7b29e69cc.
