### ISSUE TITLE
tikz externalize

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#55]
posted on behalf of @stefan11 
Ich wollte mal meine ganzen Bäume externalisieren, damit es etwas
schneller geht. Das funktioniert aber nicht, weil in der langsci-Klasse
Sachen mit atBeginDocument geladen werden:

http://tex.stackexchange.com/questions/352157/tikz-externalization-and-renewindex/352160#352160

Könnt Ihr das vielleicht reparieren? Ich habe es versucht, aber das ist
an vielen Stellen und ich verstehe nicht, was los ist.

**Comment by timmli** [comment]
@stefan11 On tex.sx, it is proposed to put `\tikzexternalize` within `\AtEndPreamble` after the index commands:

```latex
\AtEndPreamble{
    \makeindex
    \renewindex{default}{adx}{and}{lsNameIndexTitle}
    \tikzexternalize[prefix=external-figures/]
}
```

Two questions:
1. Did this eventually work out for you?
2. Should we go for another option that adds `\tikzexternalize[prefix=external-figures/]` at the right spot? Probably other authors would like to use it too.

**Comment by kopeckyf** [comment]
We now have rudimentary externalisation functionality, with the following limitations:

- `optimize=true` does not work as argument to `\tikzexternalize`, which increases compute time
- We don't have multi-threading yet due to `[mode=list and make]` incompatibility with `forest`.

The pertinent commits are https://github.com/langsci/langscibook/commit/9589a4cc1beb861aef987a3d40dc9adc0a108c27 and https://github.com/langsci/langscibook/commit/d9577cf4aa16c654f9a259d379efe0ba9f30ef44

Example output is in Roland Schäfers book https://github.com/rsling/egbd/tree/master/figcache

**Comment by stefan11** [comment]
Wo kann man hier "like" drücken?

**Comment by kopeckyf** [comment]
Note for future reference: @stefan11 produced his HPSG handbook (https://github.com/langsci/259) using the library `memoize` (https://github.com/sasozivanovic/memoize)
